/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.timone.gate;

import com.formdev.flatlaf.extras.FlatSVGIcon;
import com.formdev.flatlaf.intellijthemes.materialthemeuilite.FlatGitHubIJTheme;
import com.timone.connection.DbConnection;
import com.timone.main.admin.MainAdmin;
import com.timone.main.cashier.CashierForm;
import javax.swing.UIManager;
import java.awt.event.KeyEvent;
import java.awt.event.KeyListener;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.time.LocalDate;
import java.time.LocalTime;
import java.util.Random;
import javax.swing.JOptionPane;

/**
 *
 * @author Fadel
 */
public class RfidPage extends javax.swing.JFrame {
    
    private String rfidCode;
    /**
     * Creates new form LoginPage
     */
    public RfidPage() {
        UIManager.put("TextComponent.arc", 10);
        initComponents();
        setLocationRelativeTo(null);
        jPasswordField1.requestFocusInWindow();
        jPasswordField1.addKeyListener(new KeyListener() {
            @Override
            public void keyTyped(KeyEvent e) {
            }

            @Override
            public void keyPressed(KeyEvent e) {
                if (e.getKeyCode() == KeyEvent.VK_ENTER) {
                    // Jika tombol Enter ditekan, cek kode RFID
                    rfidCode = String.valueOf(jPasswordField1.getPassword());
                    checkRFID();
                }
            }

            @Override
            public void keyReleased(KeyEvent e) {
                // Tidak perlu aksi apa pun saat tombol dilepas
            }
        });

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jPasswordField1 = new javax.swing.JPasswordField();
        jButton31 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setAutoRequestFocus(false);
        setResizable(false);

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel1.setText("Scan disini");

        jButton1.setIcon(new FlatSVGIcon("com/timone/icon/svg/rfid.svg", 2.3f));
        jButton1.setBorderPainted(false);
        jButton1.setContentAreaFilled(false);
        jButton1.setDefaultCapable(false);
        jButton1.setFocusPainted(false);
        jButton1.setFocusable(false);
        jButton1.setRequestFocusEnabled(false);
        jButton1.setRolloverEnabled(false);
        jButton1.setVerifyInputWhenFocusTarget(false);

        jPasswordField1.setEditable(true);

        jButton31.setIcon(new FlatSVGIcon("com/timone/icon/svg/exit.svg", 1.3f));
        jButton31.setBorderPainted(false);
        jButton31.setContentAreaFilled(false);
        jButton31.setFocusPainted(false);
        jButton31.setFocusable(false);
        jButton31.setRequestFocusEnabled(false);
        jButton31.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton31ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(103, 103, 103)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jPasswordField1)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(48, 48, 48)
                        .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(123, 123, 123)
                        .addComponent(jButton31, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(50, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jButton31, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 12, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addComponent(jPasswordField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(29, 29, 29))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton31ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton31ActionPerformed
        LoginPage.main(new String[]{});
        this.dispose();
    }//GEN-LAST:event_jButton31ActionPerformed
    
    private void checkRFID() {
        Connection conn = null;
        PreparedStatement pstmt = null;
        ResultSet rs = null;

        try {
            conn = DbConnection.getConnection();

            // Periksa tabel 'about' untuk kode RFID
            String aboutQuery = "SELECT * FROM about WHERE rfid = ?";
            pstmt = conn.prepareStatement(aboutQuery);
            pstmt.setString(1, rfidCode);
            rs = pstmt.executeQuery();

            if (rs.next()) {
                // Jika kode RFID ditemukan di tabel 'about', buka MainAdmin
                MainAdmin.main(new String[]{});

                this.dispose();
                return; // Keluar dari metode setelah membuka MainAdmin
            }

            // Periksa tabel 'akun_karyawan' untuk kode RFID
            String karyawanQuery = "SELECT kode_user, nama FROM akun_karyawan WHERE rfid = ?";
            pstmt = conn.prepareStatement(karyawanQuery);
            pstmt.setString(1, rfidCode);
            rs = pstmt.executeQuery();

            if (rs.next()) {
                String kodeUser = rs.getString("kode_user");
                String nama = rs.getString("nama");

                // Jika kode RFID ditemukan di tabel 'akun_karyawan', buka CashierForm
                CashierForm cashierForm = new CashierForm();
                cashierForm.setNama(nama); // Set nama pengguna di CashierForm
                cashierForm.setLocationRelativeTo(null);
                cashierForm.setVisible(true); // Pastikan CashierForm ditampilkan setelah semua pengaturan selesai
                insertAbsensi(conn, kodeUser); // Masukkan log absensi menggunakan kode_user
                this.dispose();
                return; // Keluar dari metode setelah membuka CashierForm
            }

            // Jika kode RFID tidak ditemukan di kedua tabel
            JOptionPane.showMessageDialog(this, "Akses tidak ditemukan", "Error", JOptionPane.ERROR_MESSAGE);
        } catch (SQLException ex) {
            ex.printStackTrace();
            JOptionPane.showMessageDialog(this, "Terjadi kesalahan saat memeriksa kode RFID.", "Error", JOptionPane.ERROR_MESSAGE);
        } finally {
            // Tutup semua sumber daya
            try {
                if (rs != null) rs.close();
                if (pstmt != null) pstmt.close();
                if (conn != null) conn.close();
            } catch (SQLException ex) {
                ex.printStackTrace();
            }
        }
    }
    public void insertAbsensi(Connection conn, String kodeUser) throws SQLException {
        try {
            // Generate unique absensi ID
            String idAbsensi = generateUniqueAbsensiId(conn);

            // Check if absensi entry already exists for the kode_user on today's date
            boolean isAlreadyLogged = false;
            try (PreparedStatement stmtCheckAbsensi = conn.prepareStatement("SELECT COUNT(*) FROM absensi WHERE kode_user=? AND tanggal_kehadiran=?")) {
                stmtCheckAbsensi.setString(1, kodeUser);
                stmtCheckAbsensi.setDate(2, java.sql.Date.valueOf(LocalDate.now()));
                try (ResultSet rs = stmtCheckAbsensi.executeQuery()) {
                    if (rs.next()) {
                        int count = rs.getInt(1);
                        isAlreadyLogged = count > 0;
                    }
                }
            }

            // If absensi entry does not exist for the kode_user on today's date, insert a new absensi log
            if (!isAlreadyLogged) {
                try (PreparedStatement stmtInsertAbsensi = conn.prepareStatement("INSERT INTO absensi (id_absensi, kode_user, tanggal_kehadiran, waktu) VALUES (?, ?, ?, ?)")) {
                    stmtInsertAbsensi.setString(1, idAbsensi);
                    stmtInsertAbsensi.setString(2, kodeUser);
                    stmtInsertAbsensi.setDate(3, java.sql.Date.valueOf(LocalDate.now())); // Today's date
                    stmtInsertAbsensi.setTime(4, java.sql.Time.valueOf(LocalTime.now())); // Current time
                    stmtInsertAbsensi.executeUpdate();
                }
            }
        } catch (SQLException e) {
            // Handle any SQL exceptions
            e.printStackTrace();
        }
    }
    
        // Metode untuk menghasilkan ID Absensi unik dengan panjang 10 angka
        private String generateUniqueAbsensiId(Connection conn) throws SQLException {
            Random random = new Random();
            String idAbsensi;
            boolean isUnique;

            do {
                idAbsensi = String.format("%010d", random.nextInt(1_000_000_000));

                // Check if idAbsensi already exists in the database
                try (PreparedStatement stmtCheckId = conn.prepareStatement("SELECT COUNT(*) FROM absensi WHERE id_absensi=?")) {
                    stmtCheckId.setString(1, idAbsensi);
                    try (ResultSet rs = stmtCheckId.executeQuery()) {
                        isUnique = !rs.next() || rs.getInt(1) == 0;
                    }
                }
            } while (!isUnique);

            return idAbsensi;
        }

    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
    FlatGitHubIJTheme.setup();
    java.awt.EventQueue.invokeLater(new Runnable() {
        public void run() {
            RfidPage rfidPage = new RfidPage();
            rfidPage.setVisible(true);
        }
    });
}

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton31;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPasswordField jPasswordField1;
    // End of variables declaration//GEN-END:variables
}
